name: CI
on:
  push:

jobs:
  # Enable later
  #freebsd-cross-build:
  #  name: Cross-Build for FreeBSD
  #  runs-on: 'ubuntu-22.04'
  #  steps:
  #  - uses: actions/checkout@v3

  #  - name: Setup Rust toolchain
  #    run: rustup show

  #  - name: Install cross compilation tool
  #    run: cargo install cross

  #  - name: Build FreeBSD tool
  #    run: cross build --target=x86_64-unknown-freebsd

  #  - name: Upload FreeBSD App
  #    uses: actions/upload-artifact@v3
  #    with:
  #      name: qmk_hid_freebsd
  #      path: target/x86_64-unknown-freebsd/debug/qmk_hid

  build:
    name: Build Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Setup Rust toolchain
      run: rustup show

    - name: Build Linux tool
      run: |
        cargo build
        cargo build --release

    - name: Check if Linux tool can start
      run: cargo run -- --help

    - name: Upload Linux Debug tool
      uses: actions/upload-artifact@v3
      with:
        name: qmk_hid_debug_linux
        path: target/debug/qmk_hid

    - name: Upload Linux Relase tool
      uses: actions/upload-artifact@v3
      with:
        name: qmk_hid_linux
        path: target/release/qmk_hid

  build-windows:
    name: Build Windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust toolchain
      run: rustup show

    - name: Build Windows tool
      run: |
        cargo build
        cargo build --release

    - name: Check if Windows tool can start
      run: cargo run -- --help

    - name: Upload Windows Debug App
      uses: actions/upload-artifact@v3
      with:
        name: qmk_hid_debug_windows
        path: target/debug/qmk_hid.exe

    - name: Upload Windows Release App
      uses: actions/upload-artifact@v3
      with:
        name: qmk_hid_windows
        path: target/release/qmk_hid.exe

  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Setup Rust toolchain
      run: rustup show

    - name: Run cargo fmt
      run: cargo fmt --all -- --check

    - name: Run cargo clippy
      run: cargo clippy -- -D warnings

  build-gui:
    name: Build Windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Create Executable
      uses: Martin005/pyinstaller-action@main
      with:
        python_ver: '3.11'
        spec: qmk_gui.py
        requirements: 'requirements.txt'
        upload_exe_with_name: 'qmk_gui.py'
        options: --onefile, --name "qmk_gui", --windowed
